SELECT 1;

INSERT INTO CRYPTO_USER (CREATED_AT, DELETED_AT, UPDATED_AT, CRYPTO_WALLET_ADDRESS, CVU, EMAIL, LAST_NAME, NAME, PASSWORD, POINTS) VALUES (CURRENT_TIMESTAMP,NULL,CURRENT_TIMESTAMP,'12345679','1111111111111111111111','fabi@test.com','Frangella','Fabian','{bcrypt}$2a$10$y5zuwUGdKKgAVQCXphtzKOMmH.8NiLCEJZPQ0XiezGvs7g6xYFlCi',0);
INSERT INTO CRYPTO_USER (CREATED_AT, DELETED_AT, UPDATED_AT, CRYPTO_WALLET_ADDRESS, CVU, EMAIL, LAST_NAME, NAME, PASSWORD, POINTS) VALUES (CURRENT_TIMESTAMP,NULL,CURRENT_TIMESTAMP,'12345679','1111111111111111111111','andy@test.com','Mora','Andres','{bcrypt}$2a$10$iZDqpk22QRevVh4KeH702..6PAfXHDOcW70sgkagbHficanLDvSuC',0);

INSERT INTO CRYPTO_ACTIVE (CREATED_AT, DELETED_AT, UPDATED_AT, QUANTITY, TYPE, USER_ID) VALUES
(CURRENT_TIMESTAMP,null,CURRENT_TIMESTAMP,10,0,1),
(CURRENT_TIMESTAMP,null,CURRENT_TIMESTAMP,10,1,1),
(CURRENT_TIMESTAMP,null,CURRENT_TIMESTAMP,10,2,1),
(CURRENT_TIMESTAMP,null,CURRENT_TIMESTAMP,10,3,1),
(CURRENT_TIMESTAMP,null,CURRENT_TIMESTAMP,10,4,1),
(CURRENT_TIMESTAMP,null,CURRENT_TIMESTAMP,10,5,1),
(CURRENT_TIMESTAMP,null,CURRENT_TIMESTAMP,10,6,1),
(CURRENT_TIMESTAMP,null,CURRENT_TIMESTAMP,10,7,1),
(CURRENT_TIMESTAMP,null,CURRENT_TIMESTAMP,10,8,1),
(CURRENT_TIMESTAMP,null,CURRENT_TIMESTAMP,10,9,1),
(CURRENT_TIMESTAMP,null,CURRENT_TIMESTAMP,10,10,1),
(CURRENT_TIMESTAMP,null,CURRENT_TIMESTAMP,10,11,1),
(CURRENT_TIMESTAMP,null,CURRENT_TIMESTAMP,10,12,1),
(CURRENT_TIMESTAMP,null,CURRENT_TIMESTAMP,10,13,1),
(CURRENT_TIMESTAMP,null,CURRENT_TIMESTAMP,10,0,2),
(CURRENT_TIMESTAMP,null,CURRENT_TIMESTAMP,10,1,2),
(CURRENT_TIMESTAMP,null,CURRENT_TIMESTAMP,10,2,2),
(CURRENT_TIMESTAMP,null,CURRENT_TIMESTAMP,10,3,2),
(CURRENT_TIMESTAMP,null,CURRENT_TIMESTAMP,10,4,2),
(CURRENT_TIMESTAMP,null,CURRENT_TIMESTAMP,10,5,2),
(CURRENT_TIMESTAMP,null,CURRENT_TIMESTAMP,10,6,2),
(CURRENT_TIMESTAMP,null,CURRENT_TIMESTAMP,10,7,2),
(CURRENT_TIMESTAMP,null,CURRENT_TIMESTAMP,10,8,2),
(CURRENT_TIMESTAMP,null,CURRENT_TIMESTAMP,10,9,2),
(CURRENT_TIMESTAMP,null,CURRENT_TIMESTAMP,10,10,2),
(CURRENT_TIMESTAMP,null,CURRENT_TIMESTAMP,10,11,2),
(CURRENT_TIMESTAMP,null,CURRENT_TIMESTAMP,10,12,2),
(CURRENT_TIMESTAMP,null,CURRENT_TIMESTAMP,10,13,2);

INSERT INTO CRYPTO_PRICE (CREATED_AT, DELETED_AT, UPDATED_AT, CRYPTO_CURRENCY_TYPE, PRICE, TIME)
SELECT CREATED_AT, DELETED_AT, UPDATED_AT, TYPE, 10.0, CREATED_AT FROM CRYPTO_ACTIVE WHERE USER_ID = 1;

-- Inserts de prueba para CRYPTO_PRICE consolidado por hora
INSERT INTO CRYPTO_PRICE (CREATED_AT, DELETED_AT, UPDATED_AT, CRYPTO_CURRENCY_TYPE, PRICE, TIME)
VALUES

(NOW(), NULL, NOW(), 0, 100.50, DATEADD('MINUTE', -240, CURRENT_TIMESTAMP)),
(NOW(), NULL, NOW(), 0, 101.75, DATEADD('MINUTE', -230, CURRENT_TIMESTAMP)),
(NOW(), NULL, NOW(), 0, 102.25, DATEADD('MINUTE', -220, CURRENT_TIMESTAMP)),

(NOW(), NULL, NOW(), 0, 99.95, DATEADD('MINUTE', -180, CURRENT_TIMESTAMP)),
(NOW(), NULL, NOW(), 0, 100.40, DATEADD('MINUTE', -170, CURRENT_TIMESTAMP)),
(NOW(), NULL, NOW(), 0, 98.75, DATEADD('MINUTE', -160, CURRENT_TIMESTAMP)),

(NOW(), NULL, NOW(), 0, 101.20, DATEADD('MINUTE', -120, CURRENT_TIMESTAMP)),
(NOW(), NULL, NOW(), 0, 103.50, DATEADD('MINUTE', -110, CURRENT_TIMESTAMP)),
(NOW(), NULL, NOW(), 0, 102.15, DATEADD('MINUTE', -100, CURRENT_TIMESTAMP)),

(NOW(), NULL, NOW(), 0, 97.45, DATEADD('MINUTE', -60, CURRENT_TIMESTAMP)),
(NOW(), NULL, NOW(), 0, 98.90, DATEADD('MINUTE', -50, CURRENT_TIMESTAMP)),
(NOW(), NULL, NOW(), 0, 99.65, DATEADD('MINUTE', -40, CURRENT_TIMESTAMP)),

(NOW(), NULL, NOW(), 0, 100.10, DATEADD('MINUTE', -200, CURRENT_TIMESTAMP)),
(NOW(), NULL, NOW(), 0, 101.00, DATEADD('MINUTE', -150, CURRENT_TIMESTAMP)),
(NOW(), NULL, NOW(), 0, 99.80, DATEADD('MINUTE', -130, CURRENT_TIMESTAMP)),
(NOW(), NULL, NOW(), 0, 97.65, DATEADD('MINUTE', -90, CURRENT_TIMESTAMP)),
(NOW(), NULL, NOW(), 0, 98.20, DATEADD('MINUTE', -70, CURRENT_TIMESTAMP)),
(NOW(), NULL, NOW(), 0, 100.25, DATEADD('MINUTE', -30, CURRENT_TIMESTAMP)),
(NOW(), NULL, NOW(), 0, 99.90, DATEADD('MINUTE', -20, CURRENT_TIMESTAMP)),
(NOW(), NULL, NOW(), 0, 101.50, DATEADD('MINUTE', -10, CURRENT_TIMESTAMP));